SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Toolbar\SiteTreeExtension
SilverStripe\Control\Controller:
  extensions:
    - SilverStripe\Toolbar\ControllerExtension
GlobalNav:
  snippet_path: '/assets/'
  css_file: '/toolbar/css/toolbar.css'
  regenerate_on_changed:
    - Title
    - MenuTitle
    - URLSegment
    - ParentID
    - Sort
SilverStripe\Toolbar\TemplateProvider:
  connection_timeout: 100
  transfer_timeout: 200
SilverStripe\Control\Director:
  rules:
    'toolbar//$Action': 'SilverStripe\Toolbar\Controller'
